name: Haxe-Build
on: push

jobs:
  haxe-build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1.1.3
        with:
          haxe-version: 4.0.5
      - run: |
        haxe -version
        haxelib install main.hxml --always
        haxelib install renderer.hxml --always
        haxelib git heaps https://github.com/HeapsIO/heaps.git --always
        haxelib git deepnightLibs https://github.com/deepnight/deepnightLibs.git --always
        haxelib list
        haxe main.debug.hxml
        haxe renderer.debug.hxml
        haxe main.hxml
        haxe renderer.hxml
